export enum EconomyTypes {
    Colonial,
    Balanced,
    Martial,
    Agricultural,
    Seaborne,
    SilkRoad,
    Aristocratic,
    Dwarven,
    Elven,
    Gnomish
}

export const EconomyTypeData = {
    [EconomyTypes.Colonial]: {
        name: "Colonial",
        supply: {
            food: 0.6,
            beer: 0.6,
            leather: 0.6,
            artisinal: 0.6,
            livestock: 0.5,
            ornamental: 0.4,
            enchanted: 0,
            timber: 1.5,
            tools: 0.4,
            common_ores: 2,
            medical: 0.4,
            rare_ores: 2,
            gems: 2,
            runes: 0,
            arms: 0.1,
            books: 0.1,
            enchanted_arms: 0,
            charcoal: 0.8
        },
        demand: {
            food: 1.5,
            beer: 1.2,
            leather: 1.2,
            artisinal: 1.2,
            livestock: 1.4,
            ornamental: 0.5,
            enchanted: 0,
            timber: 0.2,
            tools: 1.5,
            common_ores: 0.2,
            medical: 1.4,
            rare_ores: 0.1,
            gems: 0.1,
            runes: 0,
            arms: 0.5,
            books: 0.1,
            enchanted_arms: 0,
            charcoal: 0
        }
    },
    [EconomyTypes.Balanced]: {
        name: "Balanced",
        supply: {
            food: 1.1,
            beer: 0.6,
            leather: 1.1,
            artisinal: 1.1,
            livestock: 1.1,
            ornamental: 1.1,
            enchanted: 0.8,
            timber: 1.1,
            tools: 1.1,
            common_ores: 1.1,
            medical: 1.2,
            rare_ores: 0.9,
            gems: 0.9,
            runes: 0.3,
            arms: 1.2,
            books: 0.8,
            enchanted_arms: 0.75,
            charcoal: 0.4
        },
        demand: {
            food: 1,
            beer: 0.5,
            leather: 0.9,
            artisinal: 0.9,
            livestock: 0.9,
            ornamental: 0.9,
            enchanted: 1.2,
            timber: 0.9,
            tools: 0.9,
            common_ores: 0.9,
            medical: 0.8,
            rare_ores: 1.1,
            gems: 1.1,
            runes: 0.5,
            arms: 0.8,
            books: 1.2,
            enchanted_arms: 1.4,
            charcoal: 1.5
        }
    },
    [EconomyTypes.Martial]: {
        name: "Martial",
        supply: {
            food: 0.8,
            beer: 0.4,
            leather: 0.7,
            artisinal: 0.5,
            livestock: 0.8,
            ornamental: 0.7,
            enchanted: 0.2,
            timber: 0.5,
            tools: 0.4,
            common_ores: 0.2,
            medical: 2.4,
            rare_ores: 0.4,
            gems: 0.2,
            runes: 0.1,
            arms: 1.8,
            books: 0.1,
            enchanted_arms: 1.2,
            charcoal: 0.8
        },
        demand: {
            food: 1,
            beer: 0.4,
            leather: 1.2,
            artisinal: 0.7,
            livestock: 2.4,
            ornamental: 0.4,
            enchanted: 0.2,
            timber: 1.6,
            tools: 1.5,
            common_ores: 2.4,
            medical: 2.4,
            rare_ores: 1.4,
            gems: 0.2,
            runes: 0.1,
            arms: 3,
            books: 0.1,
            enchanted_arms: 2.5,
            charcoal: 1.5
        }
    },
    [EconomyTypes.Agricultural]: {
        name: "Agricultural",
        supply: {
            food: 1.3,
            beer: 1.5,
            leather: 1.5,
            artisinal: 0.7,
            livestock: 1.6,
            ornamental: 0.4,
            enchanted: 0.2,
            timber: 1.4,
            tools: 0.7,
            common_ores: 0.4,
            medical: 0.4,
            rare_ores: 0.2,
            gems: 0.3,
            runes: 0,
            arms: 0.5,
            books: 0.2,
            enchanted_arms: 0.1,
            charcoal: 0.2
        },
        demand: {
            food: 0.8,
            beer: 0.6,
            leather: 0.3,
            artisinal: 1.4,
            livestock: 0.3,
            ornamental: 0.4,
            enchanted: 0.1,
            timber: 0.4,
            tools: 2,
            common_ores: 0.6,
            medical: 0.4,
            rare_ores: 0.2,
            gems: 0.1,
            runes: 0,
            arms: 0.7,
            books: 0.2,
            enchanted_arms: 0.1,
            charcoal: 0.1
        }
    },
    [EconomyTypes.Seaborne]: {
        name: "Seaborne",
        supply: {
            food: 1.4,
            beer: 1.2,
            leather: 1.2,
            artisinal: 1.4,
            livestock: 1,
            ornamental: 1.5,
            enchanted: 0.6,
            timber: 0.4,
            tools: 1.4,
            common_ores: 1.2,
            medical: 1.5,
            rare_ores: 1.1,
            gems: 1.4,
            runes: 0.4,
            arms: 1.2,
            books: 1.5,
            enchanted_arms: 0.6,
            charcoal: 0.1
        },
        demand: {
            food: 1,
            beer: 0.3,
            leather: 0.3,
            artisinal: 0.2,
            livestock: 0.6,
            ornamental: 0.6,
            enchanted: 1.3,
            timber: 2.4,
            tools: 0.8,
            common_ores: 0.9,
            medical: 0.5,
            rare_ores: 0.7,
            gems: 0.8,
            runes: 0.2,
            arms: 0.8,
            books: 0.75,
            enchanted_arms: 1.2,
            charcoal: 0.1
        }
    },
    [EconomyTypes.SilkRoad]: {
        name: "Silk Road",
        supply: {
            food: 0.4,
            beer: 0.3,
            leather: 0.5,
            artisinal: 1.2,
            livestock: 1.1,
            ornamental: 1.5,
            enchanted: 1.8,
            timber: 0.2,
            tools: 0.4,
            common_ores: 0.4,
            medical: 0.4,
            rare_ores: 1.5,
            gems: 0.7,
            runes: 0.5,
            arms: 0.2,
            books: 1.5,
            enchanted_arms: 1.4,
            charcoal: 0.7
        },
        demand: {
            food: 1,
            beer: 0.4,
            leather: 0.5,
            artisinal: 1.2,
            livestock: 1.1,
            ornamental: 0.4,
            enchanted: 0.5,
            timber: 0.4,
            tools: 0.4,
            common_ores: 0.4,
            medical: 0.4,
            rare_ores: 1.2,
            gems: 1.2,
            runes: 0.6,
            arms: 0.2,
            books: 1.2,
            enchanted_arms: 0.4,
            charcoal: 0.2
        }
    },
    [EconomyTypes.Aristocratic]: {
        name: "Aristocratic",
        supply: {
            food: 1.5,
            beer: 1,
            leather: 1.6,
            artisinal: 0.3,
            livestock: 1.8,
            ornamental: 0.25,
            enchanted: 0.05,
            timber: 1.8,
            tools: 0.3,
            common_ores: 1.5,
            medical: 1,
            rare_ores: 1.25,
            gems: 2,
            runes: 0.1,
            arms: 0.4,
            books: 1.6,
            enchanted_arms: 0.2,
            charcoal: 0.2
        },
        demand: {
            food: 1,
            beer: 0.4,
            leather: 0.3,
            artisinal: 1.6,
            livestock: 0.4,
            ornamental: 2.4,
            enchanted: 3,
            timber: 0.3,
            tools: 1.5,
            common_ores: 0.2,
            medical: 1.5,
            rare_ores: 0.3,
            gems: 0.1,
            runes: 0.2,
            arms: 1.8,
            books: 1,
            enchanted_arms: 1.5,
            charcoal: 2.5
        }
    },
    [EconomyTypes.Dwarven]: {
        name: "Dwarven",
        supply: {
            food: 1,
            beer: 1.2,
            leather: 0.6,
            artisinal: 2,
            livestock: 0.2,
            ornamental: 2,
            enchanted: 1.5,
            timber: 0.4,
            tools: 1.5,
            common_ores: 3,
            medical: 0.5,
            rare_ores: 3,
            gems: 3,
            runes: 2,
            arms: 1.5,
            books: 0.5,
            enchanted_arms: 2,
            charcoal: 0.1
        },
        demand: {
            food: 1,
            beer: 1,
            leather: 1,
            artisinal: 1,
            livestock: 0.25,
            ornamental: 0.3,
            enchanted: 0.05,
            timber: 1.5,
            tools: 0.8,
            common_ores: 0.6,
            medical: 0.75,
            rare_ores: 0.4,
            gems: 0.5,
            runes: 0.25,
            arms: 1,
            books: 1.5,
            enchanted_arms: 1.5,
            charcoal: 4
        }
    },
    [EconomyTypes.Elven]: {
        name: "Elven",
        supply: {
            food: 0.25,
            beer: 0.2,
            leather: 0.15,
            artisinal: 0.1,
            livestock: 0,
            ornamental: 1.5,
            enchanted: 8,
            timber: 0,
            tools: 0.25,
            common_ores: 0.1,
            medical: 0.15,
            rare_ores: 0.15,
            gems: 0.15,
            runes: 0,
            arms: 0.15,
            books: 4,
            enchanted_arms: 10,
            charcoal: 0
        },
        demand: {
            food: 1,
            beer: 0.1,
            leather: 0.1,
            artisinal: 0.1,
            livestock: 0,
            ornamental: 0.2,
            enchanted: 0.15,
            timber: 0,
            tools: 0.15,
            common_ores: 3,
            medical: 0.1,
            rare_ores: 4,
            gems: 4,
            runes: 0,
            arms: 0.2,
            books: 0.15,
            enchanted_arms: 0.1,
            charcoal: 0
        }
    },
    [EconomyTypes.Gnomish]: {
        name: "Gnomish",
        supply: {
            food: 0.9,
            beer: 0.5,
            leather: 0.8,
            artisinal: 0.8,
            livestock: 0.5,
            ornamental: 0.7,
            enchanted: 1.3,
            timber: 0.8,
            tools: 0.9,
            common_ores: 0.7,
            medical: 0.8,
            rare_ores: 0.6,
            gems: 0.7,
            runes: 1.2,
            arms: 0.4,
            books: 6,
            enchanted_arms: 1.4,
            charcoal: 0.4
        },
        demand: {
            food: 1,
            beer: 0.1,
            leather: 0.1,
            artisinal: 0.1,
            livestock: 0,
            ornamental: 0.2,
            enchanted: 0.15,
            timber: 0,
            tools: 0.15,
            common_ores: 3,
            medical: 0.1,
            rare_ores: 4,
            gems: 4,
            runes: 0,
            arms: 0.2,
            books: 0.15,
            enchanted_arms: 0.1,
            charcoal: 0
        }
    },
}